apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  labels:
    "argo-cd": "true"
    "helm": "true"
    "system": "true"
spec:
  project: default
  source:
    targetRevision: HEAD
    repoURL: https://github.com/sahil-R/RE-TEST.git
    path: helm-charts/istio/gateway
    helm:
      releaseName: istio-gateway
      valuesObject:
        defaults:
          service:
            type: NodePort
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-ingress
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle    # Example field to ignore
    - /webhooks/0/failurePolicy            # Example diff causing issues
  syncPolicy:
    automated:
      prune: true
      selfHeal: true