apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  labels:
    "argo-cd": "true"
    "helm": "true"
    "system": "true"
spec:
  project: default
  source:
    chart: istiod
    targetRevision: 1.23.1
    repoURL: https://istio-release.storage.googleapis.com/charts
    helm:
      releaseName: istiod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle    # Example field to ignore
    - /webhooks/0/failurePolicy  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true