apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  labels:
    "argo-cd": "true"
    "helm": "true"
    "system": "true"
spec:
  project: default
  source:
    targetRevision: HEAD
    repoURL: https://github.com/sahil-R/RE-TEST.git
    path: helm-charts/istio/kiali-server
    helm:
      releaseName: kiali
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true